<?php

namespace Ens\JobBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getWithJobs(){

		$query = $this->createQueryBuilder('c')
					->where('j.expires_at > :date')
					->join('c.jobs', 'j')
					->setParameter('date', date('Y-m-d H:i:s',time()))
					->andWhere('j.is_activated = 1')
					->getQuery();

		return $query->getResult();
	}

	public function getAllCategories(){
		$query = $this->createQueryBuilder('c')
						->getQuery();

		return $query->getResult();
	}

}
